We obtained permission from the authors of the MAGE dataset to generate Watershed-SV results for only a subset of 400 individuals-gene pairs, stored in `400_random_pairs.tsv`. Here we subset the data before running the Watershed algorithm and enrichment analysis.

## Setup

In [1]:
library(AnVILGCP)
library(data.table)
anno_metadata_tbl    <- setDT(avtable('anno_metadata'))
watershed_sv_run_tbl <- setDT(avtable('watershed_sv_run'))

system(paste('gcloud storage cp',watershed_sv_run_tbl$combined_annotations,'.'))
system('gcloud storage cp $WORKSPACE_BUCKET/data/derived/mage_expression-watershed_sv_input.tsv .')
system(paste('gcloud storage cp', anno_metadata_tbl[anno_metadata_id=='400_gene_individual_pairs', file], '.'))

Registered S3 methods overwritten by 'AnVIL':
  method                         from
  print.avworkflow_configuration AnVILGCP
  print.gcloud_sdk_result        AnVILGCP

In [2]:
watershed_sv_run_tbl$combined_annotations

[1] "gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/submissions/946b3271-a0e3-40e7-a04b-8ec556c5716a/Watershed_SV/685a7e8a-a327-41b9-a493-c458581116a8/call-combine_annotations_ABC/combined_dataset.tsv"

Here, the gene-individual pair list of outliers created in notebook 3 (`mage_expression-watershed_sv_input.tsv`) and the gene-individual pair annotations from the workflow (`combined_dataset.tsv`) are subset to the unique individuals & genes in the predetermined `400_random_pairs.csv` file.

In [3]:
dt1 <- fread('mage_expression-watershed_sv_input.tsv')[, gene := sub('\\..*','',gene    )]
dt2 <- fread('combined_dataset.tsv'                  )[, gene := sub(  ':.*','',GeneName)]

samps <- fread('400_random_pairs.csv')$SubjectID
genes <- fread('400_random_pairs.csv')$GeneName |> sub(pat=':.*', rep='')

dt1_400 <- dt1[Ind       %in% samps & gene %in% genes]
dt2_400 <- dt2[SubjectID %in% samps & gene %in% genes]

fwrite(dt1_400, 'mage_expression-watershed_sv_input-400_random_pairs.tsv', sep='\t')
fwrite(dt2_400, 'combined_dataset-400_random_pairs.tsv',                   sep='\t')

system('gcloud storage cp combined_dataset-400_random_pairs.tsv $WORKSPACE_BUCKET/data/derived/')
system('gcloud storage cp mage_expression-watershed_sv_input-400_random_pairs.tsv $WORKSPACE_BUCKET/data/derived/')

In [4]:
paste('Unique individuals:', length(unique(dt1_400$Ind )))
paste('Unique genes:',       length(unique(dt2_400$gene)))

dt1_400
dt2_400

[1] "Unique individuals: 242"

[1] "Unique genes: 54"

      Ind     gene            MedZ
1     NA11919 ENSG00000002822  0.94268820
2     NA11933 ENSG00000002822  1.72268868
3     NA12286 ENSG00000002822 -0.56629586
4     NA12762 ENSG00000002822 -0.13052663
5     NA12812 ENSG00000002822 -0.08290415
6     NA12828 ENSG00000002822 -1.03830134
7     NA12889 ENSG00000002822 -0.02641814
8     NA18504 ENSG00000002822  0.67707256
9     NA18507 ENSG00000002822 -0.91429718
10    NA18522 ENSG00000002822 -0.51613778
11    NA18531 ENSG00000002822  0.08406062
12    NA18553 ENSG00000002822 -0.84377616
13    NA18555 ENSG00000002822 -0.18124582
14    NA18557 ENSG00000002822  0.44979574
15    NA18596 ENSG00000002822 -1.15168507
16    NA18621 ENSG00000002822  1.35383829
17    NA18749 ENSG00000002822  0.77510065
18    NA18865 ENSG00000002822  0.65110614
19    NA18874 ENSG00000002822 -0.73240947
20    NA18876 ENSG00000002822 -1.23146169
21    NA18877 ENSG00000002822  0.41152728
22    NA18878 ENSG00000002822 -0.57386327
23    NA18879 ENSG00000002822 -1.60090952
24    NA18915 ENSG00000002822 -1.32089338
25    NA18963 ENSG00000002822 -0.30126033
26    NA18977 ENSG00000002822 -1.15452080
27    NA18987 ENSG00000002822 -0.36952565
28    NA19010 ENSG00000002822  0.01623941
29    NA19028 ENSG00000002822  1.00809301
30    NA19080 ENSG00000002822 -0.53435821
⋮     ⋮       ⋮               ⋮
29737 HG03485 ENSG00000277142 -0.97499736
29738 HG03491 ENSG00000277142  0.75531060
29739 HG03499 ENSG00000277142 -0.09207433
29740 HG03514 ENSG00000277142  1.30674997
29741 HG03521 ENSG00000277142  0.41308665
29742 HG03558 ENSG00000277142  0.28976398
29743 HG03563 ENSG00000277142 -0.44301402
29744 HG03578 ENSG00000277142  1.19491153
29745 HG03604 ENSG00000277142 -0.28883259
29746 HG03631 ENSG00000277142 -0.42810806
29747 HG03646 ENSG00000277142  0.72002402
29748 HG03696 ENSG00000277142 -0.64078994
29749 HG03717 ENSG00000277142 -0.23255227
29750 HG03815 ENSG00000277142 -0.24283801
29751 HG03823 ENSG00000277142 -0.94701959
29752 HG03858 ENSG00000277142 -1.20842949
29753 HG03888 ENSG00000277142 -1.46007858
29754 HG03898 ENSG00000277142  0.54460425
29755 HG03900 ENSG00000277142 -0.55226929
29756 HG03902 ENSG00000277142  1.53395746
29757 HG03978 ENSG00000277142  0.61907943
29758 HG04002 ENSG00000277142 -0.24669443
29759 HG04059 ENSG00000277142  0.15945293
29760 HG04060 ENSG00000277142 -0.41855608
29761 HG04062 ENSG00000277142  0.97936099
29762 HG04107 ENSG00000277142  0.35724016
29763 HG04152 ENSG00000277142  0.22312912
29764 HG04155 ENSG00000277142  0.67677345
29765 HG04158 ENSG00000277142 -0.30793335
29766 HG04177 ENSG00000277142  0.25513263

    SubjectID GeneName
1   HG00146   ENSG00000174807:UW_VH_3482
2   NA18553   ENSG00000168303:DUP_gs_CNV_7_40131223_40160568
3   HG03127   ENSG00000181192:DUP_gs_CNV_10_12111903_12124450
4   HG03127   ENSG00000181192:DUP_gs_CNV_10_12102547_12113247
5   HG03097   ENSG00000140470:DEL_pindel_43036
6   HG03118   ENSG00000162734:BI_GS_DEL1_B2_P0161_179
7   HG03084   ENSG00000138639:DEL_pindel_12414
8   NA18522   ENSG00000082068:DEL_pindel_15235
9   NA19719   ENSG00000184226:DUP_uwash_chr13_66891604_66901672
10  HG02090   ENSG00000111679:BI_GS_DEL1_B2_P1966_722
11  NA20876   ENSG00000184226:BI_GS_DEL1_B3_P2161_2
12  HG01055   ENSG00000133019:UW_VH_8124
13  HG02583   ENSG00000145781:UW_VH_14273
14  HG02731   ENSG00000171759:UW_VH_4103
15  HG03247   ENSG00000051620:DEL_pindel_20533
16  NA12828   ENSG00000146731:DUP_uwash_chr7_56031072_56186821
17  HG02494   ENSG00000159377:DUP_delly_DUP23941
18  NA19338   ENSG00000107959:BI_GS_DEL1_B3_P1691_7
19  NA18621   ENSG00000172456:DEL_pindel_738
20  HG00663   ENSG00000170745:DUP_gs_CNV_2_17937146_18216823
21  HG01853   ENSG00000174807:UW_VH_13686
22  HG03135   ENSG00000152078:UW_VH_22151
23  HG00141   ENSG00000169926:DUP_uwash_chr15_31110505_31330839
24  HG01363   ENSG00000116667:BI_GS_DEL1_B2_P0185_310
25  HG02481   ENSG00000130764:DUP_gs_CNV_1_3734485_3844788
26  HG02545   ENSG00000165752:UW_VH_8079
27  HG04177   ENSG00000184226:UW_VH_16198
28  HG01125   ENSG00000116667:DEL_pindel_1695
29  NA19385   ENSG00000198876:BI_GS_DEL1_B5_P1580_84
30  NA18504   ENSG00000051620:DEL_pindel_20533
⋮   ⋮         ⋮
229 HG02471   ENSG00000168282:DEL_pindel_40224
230 NA19393   ENSG00000172403:UW_VH_8741
231 HG03091   ENSG00000184226:DUP_uwash_chr13_66891604_66901672
232 NA19404   ENSG00000082068:BI_GS_DEL1_B5_P0923_417
233 HG02429   ENSG00000138639:DEL_pindel_12421
234 HG01809   ENSG00000082068:DEL_pindel_15237
235 HG01669   ENSG00000172456:DEL_pindel_734
236 HG02026   ENSG00000184226:UW_VH_6503
237 HG01812   ENSG00000071189:DEL_pindel_21870
238 HG02580   ENSG00000165752:UW_VH_8079
239 HG03064   ENSG00000181192:DUP_uwash_chr10_12092804_12171370
240 HG03311   ENSG00000162734:BI_GS_DEL1_B2_P0161_179
241 HG00463   ENSG00000182308:BI_GS_DEL1_B3_P0735_35
242 HG03696   ENSG00000178038:DUP_gs_CNV_3_46667900_46756660
243 HG02888   ENSG00000172403:UW_VH_8741
244 HG00533   ENSG00000107959:DUP_gs_CNV_10_3179999_3227801
245 NA18749   ENSG00000172456:DEL_pindel_738
246 NA19338   ENSG00000035115:BI_GS_DEL1_B4_P0251_46
247 HG01912   ENSG00000174807:UW_VH_3482
248 HG01853   ENSG00000166387:DUP_gs_CNV_11_7545083_7650780
249 HG01988   ENSG00000184226:DUP_uwash_chr13_66891604_66901672
250 HG01965   ENSG00000116667:BI_GS_DEL1_B2_P0185_348
251 HG03166   ENSG00000063438:DUP_delly_DUP66791
252 HG01606   ENSG00000100505:BI_GS_DEL1_B5_P2261_114
253 HG02494   ENSG00000171759:BI_GS_DEL1_B2_P2062_577
254 HG02624   ENSG00000184022:DUP_gs_CNV_1_248572358_248596103
255 HG01363   ENSG00000168280:BI_GS_DEL1_B1_P0400_8
256 NA12889   ENSG00000175868:DUP_gs_CNV_11_14873676_14919955
257 HG02981   ENSG00000051620:DEL_pindel_20533
258 HG02545   ENSG00000152078:UW_VH_22151
    SVTYPE_DUP_gene_body SVTYPE_DUP_CNV_gene_body SVTYPE_DEL_CNV_gene_body
1   NA                   NA                       NA
2    1                    0                        0
3    1                    0                        0
4    1                    0                        0
5    0                    0                        0
6    0                    0                        0
7    0                    0                        0
8   NA                   NA                       NA
9    0                    0                        0
10   0                    0                        0
11   0                    0                        0
12   0                    0                        0
13   0                    0                        0
14   0                    0                        0
15  NA                   NA                       NA
16   1                    0                        0
17   1                    0                        0
18   0                    0                        0
19   0                    0                        0
20   1                    0                        0
21  NA                   NA                       NA
22   0                    0                        0
23   1                    0                        0
24   0                    0                        0
25   1                    0                        0
26   0                    0                        0
27   0                    0                        0
28   0                    0                        0
29   0                    0                        0
30  NA                   NA                       NA
⋮   ⋮                    ⋮                        ⋮
229  0                    0                        0
230 NA                   NA                       NA
231  0                    0                        0
232  0                    0                        0
233  0                    0                        0
234  0                    0                        0
235  0                    0                        0
236  0                    0                        0
237  0                    0                        0
238  0                    0                        0
239  1                    0                        0
240  0                    0                        0
241 NA                   NA                       NA
242  1                    0                        0
243 NA                   NA                       NA
244 NA                   NA                       NA
245  0                    0                        0
246 NA                   NA                       NA
247 NA                   NA                       NA
248  1                    0                        0
249  0                    0                        0
250  0                    0                        0
251  1                    0                        0
252  0                    0                        0
253 NA                   NA                       NA
254  1                    0                        0
255  0                    0                        0
256  1                    0                        0
257 NA                   NA                       NA
258  0                    0                        0
    SVTYPE_DEL_gene_body SVTYPE_INS_gene_body SVTYPE_INV_gene_body
1   NA                   NA                   NA
2    0                    0                    0
3    0                    0                    0
4    0                    0                    0
5    1                    0                    0
6    1                    0                    0
7    1                    0                    0
8   NA                   NA                   NA
9    1                    0                    0
10   1                    0                    0
11   1                    0                    0
12   1                    0                    0
13   1                    0                    0
14   1                    0                    0
15  NA                   NA                   NA
16   0                    0                    0
17   0                    0                    0
18   1                    0                    0
19   1                    0                    0
20   0                    0                    0
21  NA                   NA                   NA
22   1                    0                    0
23   0                    0                    0
24   1                    0                    0
25   0                    0                    0
26   1                    0                    0
27   1                    0                    0
28   1                    0                    0
29   1                    0                    0
30  NA                   NA                   NA
⋮   ⋮                    ⋮                    ⋮
229  1                    0                    0
230 NA                   NA                   NA
231  1                    0                    0
232  1                    0                    0
233  1                    0                    0
234  1                    0                    0
235  1                    0                    0
236  1                    0                    0
237  1                    0                    0
238  1                    0                    0
239  0                    0                    0
240  1                    0                    0
241 NA                   NA                   NA
242  0                    0                    0
243 NA                   NA                   NA
244 NA                   NA                   NA
245  1                    0                    0
246 NA                   NA                   NA
247 NA                   NA                   NA
248  0                    0                    0
249  1                    0                    0
250  1                    0                    0
251  0                    0                    0
252  1                    0                    0
253 NA                   NA                   NA
254  0                    0                    0
255  1                    0                    0
256  0                    0                    0
257 NA                   NA                   NA
258  1                    0                    0
    SVTYPE_DUP_tss_flank SVTYPE_DUP_CNV_tss_flank ⋯
1   NA                   NA                       ⋯
2    1                    0                       ⋯
3   NA                   NA                       ⋯
4   NA                   NA                       ⋯
5   NA                   NA                       ⋯
6    0                    0                       ⋯
7   NA                   NA                       ⋯
8    0                    0                       ⋯
9   NA                   NA                       ⋯
10   0                    0                       ⋯
11  NA                   NA                       ⋯
12  NA                   NA                       ⋯
13  NA                   NA                       ⋯
14  NA                   NA                       ⋯
15  NA                   NA                       ⋯
16   1                    0                       ⋯
17   1                    0                       ⋯
18  NA                   NA                       ⋯
19  NA                   NA                       ⋯
20  NA                   NA                       ⋯
21   0                    0                       ⋯
22  NA                   NA                       ⋯
23   1                    0                       ⋯
24  NA                   NA                       ⋯
25   1                    0                       ⋯
26  NA                   NA                       ⋯
27  NA                   NA                       ⋯
28  NA                   NA                       ⋯
29  NA                   NA                       ⋯
30  NA                   NA                       ⋯
⋮   ⋮                    ⋮                        ⋱
229 NA                   NA                       ⋯
230  0                    0                       ⋯
231 NA                   NA                       ⋯
232 NA                   NA                       ⋯
233 NA                   NA                       ⋯
234 NA                   NA                       ⋯
235 NA                   NA                       ⋯
236 NA                   NA                       ⋯
237 NA                   NA                       ⋯
238 NA                   NA                       ⋯
239 NA                   NA                       ⋯
240  0                    0                       ⋯
241  0                    0                       ⋯
242  1                    0                       ⋯
243  0                    0                       ⋯
244  1                    0                       ⋯
245 NA                   NA                       ⋯
246 NA                   NA                       ⋯
247 NA                   NA                       ⋯
248 NA                   NA                       ⋯
249 NA                   NA                       ⋯
250 NA                   NA                       ⋯
251 NA                   NA                       ⋯
252 NA                   NA                       ⋯
253 NA                   NA                       ⋯
254  1                    0                       ⋯
255 NA                   NA                       ⋯
256  1                    0                       ⋯
257 NA                   NA                       ⋯
258 NA                   NA                       ⋯
    num_enhancers_cell_types_tes_flank is_ABC_SV_tes_flank
1   NA                                 NA
2   NA                                 NA
3   NA                                  1
4   NA                                 NA
5   NA                                 NA
6   NA                                 NA
7   NA                                 NA
8   NA                                 NA
9   NA                                 NA
10  NA                                 NA
11  NA                                 NA
12  NA                                 NA
13  NA                                 NA
14  NA                                 NA
15  NA                                 NA
16   8                                  1
17  NA                                 NA
18  NA                                 NA
19  NA                                 NA
20  NA                                 NA
21  NA                                 NA
22  NA                                 NA
23  NA                                 NA
24  NA                                 NA
25  NA                                  1
26  NA                                 NA
27  NA                                 NA
28  NA                                 NA
29  NA                                 NA
30  NA                                 NA
⋮   ⋮                                  ⋮
229 NA                                 NA
230 NA                                 NA
231 NA                                 NA
232 NA                                 NA
233 NA                                 NA
234 NA                                 NA
235 NA                                 NA
236 NA                                 NA
237 NA                                 NA
238 NA                                 NA
239  2                                  1
240 NA                                 NA
241 NA                                 NA
242 NA                                 NA
243 NA                                 NA
244 NA                                 NA
245 NA                                 NA
246 NA                                 NA
247 NA                                 NA
248 NA                                 NA
249 NA                                 NA
250 NA                                 NA
251 NA                                 NA
252 NA                                 NA
253 NA                                 NA
254  2                                 NA
255 NA                                 NA
256 NA                                 NA
257 NA                                 NA
258 NA                                 NA
    mean_GC_content_tes_flank top10_LINSIGHT_tes_flank top10_phastCON_tes_flank
1   48.35777                  0.13788000               0.6911
2         NA                          NA                   NA
3   45.63265                  0.51951611               0.7593
4         NA                          NA                   NA
5         NA                          NA                   NA
6         NA                          NA                   NA
7         NA                          NA                   NA
8         NA                          NA                   NA
9         NA                          NA                   NA
10        NA                          NA                   NA
11        NA                          NA                   NA
12        NA                          NA                   NA
13        NA                          NA                   NA
14  36.07570                  0.05204305               0.9848
15  49.13043                  0.04801141               0.4367
16  47.56000                  0.95809681               1.0000
17  44.43626                  0.98880230               1.0000
18        NA                          NA                   NA
19        NA                          NA                   NA
20        NA                          NA                   NA
21        NA                          NA                   NA
22        NA                          NA                   NA
23        NA                          NA                   NA
24        NA                          NA                   NA
25  63.33000                  0.91935900               1.0000
26        NA                          NA                   NA
27        NA                          NA                   NA
28        NA                          NA                   NA
29        NA                          NA                   NA
30  49.13043                  0.04801141               0.4367
⋮   ⋮                         ⋮                        ⋮
229       NA                          NA                   NA
230       NA                          NA                   NA
231       NA                          NA                   NA
232       NA                          NA                   NA
233       NA                          NA                   NA
234       NA                          NA                   NA
235       NA                          NA                   NA
236       NA                          NA                   NA
237       NA                          NA                   NA
238       NA                          NA                   NA
239 47.54000                  0.94782850               0.9982
240       NA                          NA                   NA
241       NA                          NA                   NA
242 56.28882                  0.06922780               0.2142
243       NA                          NA                   NA
244       NA                          NA                   NA
245       NA                          NA                   NA
246 41.86271                  0.06503090               0.9118
247 48.35777                  0.13788000               0.6911
248       NA                          NA                   NA
249       NA                          NA                   NA
250       NA                          NA                   NA
251       NA                          NA                   NA
252       NA                          NA                   NA
253 38.37217                  0.08542180               0.0000
254 34.64400                  0.07034342               0.5594
255       NA                          NA                   NA
256       NA                          NA                   NA
257 49.13043                  0.04801141               0.4367
258       NA                          NA                   NA
    top10_CADD_tes_flank max_cpgpct_tes_flank remap_crm_score_tes_flank
1   13.5710                NA                   64
2        NA                NA                   NA
3   15.7500                NA                  418
4        NA                NA                   NA
5        NA                NA                   NA
6        NA                NA                   NA
7        NA                NA                   NA
8        NA                NA                   NA
9        NA                NA                   NA
10       NA                NA                   NA
11       NA                NA                   NA
12       NA                NA                   NA
13       NA                NA                   NA
14  14.4090                NA                  165